### ISSUE TITLE
開発環境でログインする方法

### ISSUE THREAD

**Issue by suzan2go** [nasum/nasulog#23]
教えてください！

**Comment by nasum** [comment]
googleの開発キーを環境変数にセットするのです！
ENVで設定してるところがあるはず。

**Comment by nasum** [comment]
参考URL
http://www.ohmyenter.com/rails-4-1-devise-omniauth-google-oauth2-%E3%81%A7%E8%AA%8D%E8%A8%BC%E6%A9%9F%E8%83%BD%E3%82%92%E5%AE%9F%E8%A3%85%E3%81%99%E3%82%8B/

**Comment by suzan2go** [comment]
出来ました！あざす。
