### ISSUE TITLE
プロフィール編集がtextareaになっている

### ISSUE THREAD

**Issue by nasum** [nasum/nasulog#27]
プロフィール編集がtextareaになっているのがちょっと変なので`<input type="text" >`にしたい

**Comment by suzan2go** [comment]
それでいうと、`User`モデルで`name`と`email`が`text`になってるのがちょっとおかしい気がしていて、`string`で良いのではという気が！`simple_form`はその辺りよしなにやってくれるので、カラムの型を変えれば`<input type=text >`になりまする。

**Comment by nasum** [comment]
なるほどそういうことなんだ。
そしたらカラムの型を変える方針でいきますか！
